### PR TITLE
Calculator Component Class

### PR DESCRIPTION
**Pull request by AlucardSanin**
Developed just the UI of the calculator.
Used class-based components.
Once the Calculator is ready, import it and use it in your main component (App.js).

### CODE REVIEW

**Review by KDlamini — APPROVED** [review]
### Hi @AlucardSanin 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the project requirements. 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!🎊 🥳 

## Highlights 🌞 

✔️  `Calculator.js` and `App.js` components are class-based
✔️  The `App.js` main component imports `Calculator.js`
✔️  The application matches the given design
✔️  No linter errors

# Status: Approved ✔️ 

simon

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by BenMukebo — COMMENTED** [review]
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @AlucardSanin**, 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Your Design looks awesome, keep rocking :rocket: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BenMukebo** [comment]
Hey @AlucardSanin, Are you repeating a module?

**Comment by AlucardSanin** [comment]
Yes I am! Happy new year! Enviado desde Correo para Windows De: Kasongo Mukebo BenEnviado: viernes, 13 de enero de 2023 10:13 p. m.Para: AlucardSanin/math_magiciansCC: David Isea; MentionAsunto: Re: [AlucardSanin/math_magicians] Calculator Component Class (PR #2) Hey @AlucardSanin, Are you repeating a module?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by BenMukebo** [comment]
@AlucardSanin  You are repeating this module right?

**Pull request merged**
